from typing import Any, Tuple, Optional
import numpy as np

def VideoCapture(index: int) -> Any: ...
def rectangle(img: np.ndarray, pt1: Tuple[int, int], pt2: Tuple[int, int], color: Tuple[int, int, int], thickness: int) -> None: ...
def addWeighted(src1: np.ndarray, alpha: float, src2: np.ndarray, beta: float, gamma: float, dst: Optional[np.ndarray] = ...) -> np.ndarray: ...
def putText(img: np.ndarray, text: str, org: Tuple[int, int], fontFace: int, fontScale: float, color: Tuple[int, int, int], thickness: int = ...) -> None: ...
def imshow(winname: str, mat: np.ndarray) -> None: ...
def waitKey(delay: int = ...) -> int: ...
def flip(src: np.ndarray, flipCode: int) -> np.ndarray: ...
def destroyAllWindows() -> None: ...
def cvtColor(src: np.ndarray, code: int) -> np.ndarray: ...
def CascadeClassifier(filename: str) -> Any: ...

FONT_HERSHEY_SIMPLEX: int
COLOR_BGR2GRAY: int
CAP_PROP_FRAME_WIDTH: int
CAP_PROP_FRAME_HEIGHT: int

class data:
    haarcascades: str